// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAudToHa6OLjPU8PdHQPmXQA6ykiZAdU3c',
    appId: '1:756201607300:web:fa91ffe58d33af0e8f72d1',
    messagingSenderId: '756201607300',
    projectId: 'prueba-propia-dab0c',
    authDomain: 'prueba-propia-dab0c.firebaseapp.com',
    storageBucket: 'prueba-propia-dab0c.appspot.com',
    measurementId: 'G-X07Z1QZ6S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCTPBSwmHA3ko14YpS8dyhDY0GMMRaRtY',
    appId: '1:756201607300:android:cabd986348d71b3f8f72d1',
    messagingSenderId: '756201607300',
    projectId: 'prueba-propia-dab0c',
    storageBucket: 'prueba-propia-dab0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdbBMnHStDd7pOIt5MtFzyShvaPqx9Mfc',
    appId: '1:756201607300:ios:8bfe7edbd96b1bfa8f72d1',
    messagingSenderId: '756201607300',
    projectId: 'prueba-propia-dab0c',
    storageBucket: 'prueba-propia-dab0c.appspot.com',
    iosBundleId: 'com.example.proyectoPropio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdbBMnHStDd7pOIt5MtFzyShvaPqx9Mfc',
    appId: '1:756201607300:ios:8bfe7edbd96b1bfa8f72d1',
    messagingSenderId: '756201607300',
    projectId: 'prueba-propia-dab0c',
    storageBucket: 'prueba-propia-dab0c.appspot.com',
    iosBundleId: 'com.example.proyectoPropio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAudToHa6OLjPU8PdHQPmXQA6ykiZAdU3c',
    appId: '1:756201607300:web:cdd0e2dbbb8c7dc08f72d1',
    messagingSenderId: '756201607300',
    projectId: 'prueba-propia-dab0c',
    authDomain: 'prueba-propia-dab0c.firebaseapp.com',
    storageBucket: 'prueba-propia-dab0c.appspot.com',
    measurementId: 'G-4XWWEL3L2J',
  );
}
